console.log(`4 > 3 is ${4 > 3}`); // true
console.log(`4 >= 3 is ${4 >= 3}`); // true
console.log(`4 < 3 is ${4 < 3}`); // false
console.log(`4 <= 3 is ${4 <= 3}`); // false
console.log(`4 == 4 is ${4 == 4}`); // true
console.log(`4 === 4 is ${4 === 4}`); // true
console.log(`4 != 4 is ${4 != 4}`); /// false
console.log(`4 !== 4 is ${4 !== 4}`); // false
console.log(`4 != '4' is ${4 != "4"}`); // false
console.log(`4 == '4' is ${4 == "4"}`); // true
console.log(`4 === '4' is ${4 === "4"}`); // false